function cn = config()
    cn.TYPE_BARRIAR = -1;
    cn.TYPE_PEOPLE_EMPTY = 0;
    cn.TYPE_PEOPLE_FAMILIAR = 5;
    cn.TYPE_PEOPLE_UNFAMILIAR_1 = 1;
    cn.TYPE_PEOPLE_UNFAMILIAR_2 = 2;
    cn.TYPE_PEOPLE_UNFAMILIAR_3 = 3;
    cn.TYPE_PEOPLE_UNFAMILIAR_4 = 4;
end